In [1]:
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
print(os.listdir("../testing"))

['.ipynb_checkpoints', 'product.csv', 'total.csv', 'Untitled.ipynb']

In [19]:
# import movie data set and look at columns
product = pd.read_csv("../testing/product.csv")
product.columns

Index(['productid', 'nama', 'description'], dtype='object')

In [20]:
# what we need is that movie id and title
product = product.loc[:,["productid","nama"]]
product.head(10)

   productid                       nama
0          1             Indomie Goreng
1          2             Kopi Kapal Api
2          3         Gulaku Premium 1KG
3          4                  Coca Cola
4          5             Tepung Maizena
5          6                  Sariwangi
6          7              Regal Biskuit
7          8            ABC Sarden Saus
8          9             Hand Sanitizer
9         10  Nuvo Antiseptic Wet Wipes

In [21]:
# import rating data and look at columsn
rating = pd.read_csv("../testing/total.csv")
rating.columns

Index(['userid', 'productid', 'total'], dtype='object')

In [22]:
# what we need is that user id, movie id and rating
rating = rating.loc[:,["userid","productid","total"]]
rating.head(100)

    userid  productid  total
0        1        1.0    4.0
1        1        2.0    5.0
2        1        3.0    4.0
3        1        4.0    3.0
4        1        5.0    4.0
..     ...        ...    ...
95       2       46.0    3.0
96       2       47.0    3.0
97       2       48.0    3.0
98       2       49.0    4.0
99       2       50.0    3.0

[100 rows x 3 columns]

In [23]:
# then merge movie and rating data
data = pd.merge(product,rating)

In [24]:
# now lets look at our data 
data.head(100)

    productid            nama  userid  total
0           1  Indomie Goreng       1    4.0
1           1  Indomie Goreng       2    4.0
2           1  Indomie Goreng       3    3.0
3           1  Indomie Goreng       4    3.0
4           1  Indomie Goreng       5    3.0
..        ...             ...     ...    ...
95          5  Tepung Maizena      14    4.0
96          5  Tepung Maizena      15    4.0
97          5  Tepung Maizena      16    4.0
98          5  Tepung Maizena      17    5.0
99          5  Tepung Maizena      17    NaN

[100 rows x 4 columns]

In [25]:
data.shape

(1000, 4)

In [26]:
data = data.iloc[:10000,:]

In [27]:
pivot_table = data.pivot_table(index = ["userid"],columns = ["nama"],values = "total")
pivot_table.head(1000)

nama,ABC Sarden Saus,Bango Kecap Manis,Bawang Goreng Alfamart,Beng-beng,Better Sandwich Cookies,Bon Cabe Lv 15,Close Up Everfresh,Coca Cola,Garnier Skin Natural,Gatsby Pomade,...,Spaghetti La Fonte,Sponge Crunch,Sumpit,Super Bubur,Tango Choco Javamocca,Tepung Maizena,Tictac,Tisu Toilet,Tisu Wajah,Vicks Inhaler
userid,,,,,,,,,,,,,,,,,,,,,
1,4.0,5.0,2.0,5.0,4.0,2.0,5.0,3.0,5.0,4.0,...,4.0,4.0,4.0,3.0,4.0,4.0,3.0,4.0,4.0,2.0
2,4.0,4.0,5.0,2.0,4.0,4.0,4.0,2.0,2.0,3.0,...,3.0,4.0,4.0,1.0,3.0,4.0,5.0,3.0,4.0,2.0
3,NaN,3.0,5.0,5.0,3.0,1.0,3.0,2.0,3.0,1.0,...,3.0,3.0,1.0,2.0,4.0,5.0,3.0,3.0,4.0,3.0
4,1.0,5.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,4.0,...,3.0,5.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,5.0
5,5.0,3.0,4.0,3.0,4.0,2.0,4.0,5.0,4.0,4.0,...,5.0,3.0,5.0,4.0,5.0,4.0,2.0,3.0,4.0,4.0
6,5.0,3.0,4.0,3.0,4.0,2.0,4.0,5.0,4.0,4.0,...,5.0,3.0,5.0,4.0,5.0,4.0,2.0,3.0,4.0,4.0
7,5.0,4.0,4.0,2.0,4.0,4.0,4.0,5.0,2.0,3.0,...,3.0,4.0,4.0,4.0,3.0,4.0,2.0,3.0,4.0,2.0
8,5.0,5.0,4.0,3.0,3.0,5.0,3.0,5.0,5.0,4.0,...,5.0,5.0,1.0,4.0,3.0,4.0,2.0,3.0,3.0,5.0
9,3.0,5.0,5.0,4.0,5.0,4.0,3.0,2.0,4.0,4.0,...,4.0,1.0,2.0,3.0,4.0,4.0,3.0,3.0,4.0,5.0
10,4.0,4.0,1.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,...,4.0,2.0,3.0,1.0,3.0,3.0,5.0,2.0,3.0,4.0
11,4.0,4.0,2.0,3.0,4.0,5.0,3.0,3.0,3.0,3.0,...,5.0,5.0,5.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0
12,5.0,4.0,3.0,4.0,5.0,4.0,4.0,3.0,2.0,4.0,...,2.0,1.0,3.0,3.0,2.0,5.0,2.0,4.0,4.0,3.0
13,NaN,4.0,3.0,4.0,5.0,4.0,4.0,3.0,2.0,4.0,...,2.0,1.0,3.0,3.0,2.0,5.0,2.0,4.0,4.0,3.0
14,5.0,3.0,4.0,3.0,4.0,2.0,4.0,5.0,4.0,4.0,...,5.0,3.0,5.0,4.0,5.0,4.0,2.0,3.0,4.0,4.0
15,4.0,4.0,2.0,3.0,4.0,5.0,3.0,3.0,3.0,3.0,...,5.0,5.0,5.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0
16,4.0,5.0,2.0,5.0,4.0,2.0,5.0,3.0,5.0,4.0,...,4.0,4.0,4.0,3.0,4.0,4.0,3.0,4.0,4.0,2.0
17,NaN,4.0,3.0,4.0,5.0,4.0,4.0,3.0,2.0,4.0,...,2.0,1.0,3.0,3.0,2.0,5.0,2.0,4.0,4.0,3.0
18,5.0,3.0,4.0,3.0,4.0,2.0,4.0,5.0,4.0,4.0,...,5.0,3.0,5.0,4.0,5.0,4.0,2.0,3.0,4.0,4.0
19,4.0,4.0,2.0,3.0,4.0,5.0,3.0,3.0,3.0,3.0,...,5.0,5.0,5.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0
20,4.0,4.0,5.0,2.0,4.0,4.0,4.0,2.0,2.0,3.0,...,3.0,4.0,4.0,1.0,3.0,4.0,5.0,3.0,4.0,2.0
161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
product_rated = pivot_table["Gatsby Pomade"]
similarity_with_other_product = pivot_table.corrwith(product_rated)
similarity_with_other_product = similarity_with_other_product.sort_values(ascending=False)
similarity_with_other_product.head(4)

nama
Gatsby Pomade          1.000000
Pocky Cookies&Cream    0.816982
Salonpas               0.666153
Kopi Kapal Api         0.650011
dtype: float64